name = "Hoogi"
license = "MIT"
licenselink = "https://github.com/lhooge/hugo-theme-hoogi/blob/master/LICENSE"
description = "Simple responsive theme with light / dark switch"
homepage = "https://github.com/i"
tags = ["blog", "clean", "dark", "responsive", "archive"]
features = []
min_version = "0.116.1"

[author]
  name = "Lars Hoogestraat"
  homepage = "https://hoogi.eu"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
