baseURL = 'https://hugodemo.hoogi.eu/'
languageCode = "en-us"
defaultContentLanguage = "en"
title = 'Hugodemo'
theme = 'hugo-theme-hoogi'
themesdir = "../.."

math = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
paginate = 4
relativeURLs = false

[params]
    mainSections = "posts"
    useSummary = true
    sidebar = true
    description = 'An example description'

[permalinks]
    posts = "/:year/:month/:slug/"

[menu]
   [[menu.main]]
        name       = "About"
        identifier = "about"
        pageRef    = "/"
        weight     = 1

    [[menu.main]]
        name       = "Articles"
        identifier = "articles"
        pageRef    = "/posts"
        weight     = 2

    [[menu.main]]
        name       = "Archive"
        identifier = "archive"
        pageRef    = "/archive"
        weight     = 3

    [[menu.main]]
        name       = "Tags"
        identifier = "tags"
        pageRef    = "/tags"
        weight     = 4

    [[menu.main]]
        name       = "External"
        identifier = "tags"
        url        = "https://www.google.com"
        weight     = 5

    [[menu.footer]]
        name       = "Privacy Policy"
        identifier = "privacy"
        pageRef    = "/privacy"
        weight     = 1
